spring.application.name=Gatherly

server.port=9698

spring.datasource.url = jdbc:mysql://localhost:3307/event_db?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=852963

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#DDL ??? DB? ?? ??? ?? ??
spring.jpa.hibernate.ddl-auto=update

# ????? ?? ?? connection? ??? ? ??? ??
spring.jpa.open-in-view=false

#SQL Debug
spring.jpa.show-sql=true
# JPA? ???? Hibernate? ????? ??? SQL? ???? ???
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never


# JWT Configuration
jwt.secret=e4fa9999abada1971c91f871b260ba66c9f65a8b8fc6b20f1eac74eb4bf35545
jwt.expiration=86400000
